### ISSUE TITLE
Selectively disable actions per item

### ISSUE THREAD

**Issue by aeons** [smpallen99/ex_admin#186] opened 2016-08-01 12:08 UTC
Hey,

I'm wondering if it's possible to remove the buttons for actions for a member based on some condition.

I'm using the authorization example to disallow actually performing the action, but I cannot find a way to hide the option in the UI.

Any suggestions? If not, then consider this a feature request :)

👍

**Comment by smpallen99** [comment] 2016-08-01 15:33
This should already work if you have implemented the ExAdmin.Authorization protocol correctly. If your running from Hex, I suggest you try github master. The version on hex is pretty old. It is working on the project I used for the authorization example, based on master.

There is an option to defined which action_links are shown for a given model. However, it does not support conditionals. So, if your after conditional actions just for authorization, then it should work. But if your looking for conditional actions based on other conditions, it will need to be developed. If so, please describe the conditions and I'll tag this issue as a feature request.

Either way, please let me know. Thanks, Steve

**Comment by aeons** [comment] 2016-08-01 15:38
The idea is that I want everyone to be able to see the index for a resource, but only be able to edit/delete "their own" items. As far as I can see, the `authorize_action/3` function doesn't know anything about the current item being rendered.

**Comment by smpallen99** [comment] 2016-08-01 15:48
You should implement the protocol for each of your admin resources. You can then pull out the current user and authorize actions based on it. Please review the example in in the [Add authorization section in the wiki](https://github.com/smpallen99/ex_admin/wiki/Add-authorization). 

If you want further help, please post your authorization file.

Steve

**Comment by aeons** [comment] 2016-08-01 15:55
My authorization file is almost the exact same as the example. 

The query bit works as expected, you are not able to edit other users than your own.

However, the `:index` resource still renders `Edit` buttons for all other users, which leads to an error if clicked.

What I would like to do is access the id of the resource in the `authorize_action` function. I get that that is not possible for a `:new` or `:index` action, so I'm not sure the best way to solve this.

```elixir
alias MyModule.Admin.Authentication, as: Auth
alias MyModule.Admin.Authorization, as: Authz

defimpl ExAdmin.Authorization, for: MyModule.ExAdmin.User do
  def authorize_query(_defn, _conn, query, :index, _id),
    do: query
  def authorize_query(defn, conn, query, action, id),
    do: Authz.authorize_user_query(defn, conn, query, action, id, Auth.current_user(conn))

  def authorize_action(defn, conn, action),
    do: Authz.authorize_actions(defn, conn, action, Auth.current_user(conn),
          only: [:edit, :index])
end

defmodule MyModule.Admin.Authorization do
  import Ecto.Query
  require Logger

  def authorize_user_query(_, _conn, query, _, _, user) do
    id = user.id
    where(query, [u], u.id == ^id)
  end

  def authorize_actions(_defn, conn, action, user, actions) when is_atom(action) do
    # No resource ID to check on here
    only = actions[:only]
    except = actions[:except]
    cond do
      is_list(only) -> action in only
      is_list(except) -> not action in except
      true -> false
    end
  end
end
```

**Comment by smpallen99** [comment] 2016-08-01 16:48
Here is one possible implementation. You can play around with this to create a more generic solution.

```elixir
alias MyModule.Admin.Authentication, as: Auth
alias MyModule.Admin.Authorization, as: Authz

defimpl ExAdmin.Authorization, for: MyModule.ExAdmin.User do
  def authorize_query(_defn, _conn, query, :index, _id),
    do: query
  def authorize_query(defn, conn, query, action, id),
    do: Authz.authorize_user_query(defn, conn, query, action, id, Auth.current_user(conn))

  def authorize_action(defn, conn, action),
    do: Authz.authorize_user_actions(defn, conn, action, Auth.current_user(conn))
end

defmodule MyModule.Admin.Authorization do
  import Ecto.Query
  require Logger

  def authorize_user_query(_, _conn, query, _, _, user) do
    id = user.id
    where(query, [u], u.id == ^id)
  end

  def authorize_user_actions(_, _, _, %{admin: true}) when, do: true
  def authorize_user_actions(_defn, _conn, :index, _) when is_atom(action), do: true
  def authorize_user_actions(_defn, conn, :edit, user) do
    case conn.assigns[:resource] do
      %{} = resource -> resource.id == user.id
      _ -> false
    end
  end
  def authorize_user(_, _, _, _), do: false

  def authorize_actions(_defn, conn, action, user, actions) when is_atom(action) do
    # No resource ID to check on here
    only = actions[:only]
    except = actions[:except]
    cond do
      is_list(only) -> action in only
      is_list(except) -> not action in except
      true -> false
    end
  end
end
```

**Comment by aeons** [comment] 2016-08-01 16:49
Aha, thanks, will give it a go.

**Comment by smpallen99** [comment] 2016-08-01 16:49
The trick above is that you can pull the current resource from `conn.assigns[:resource]`.

**Comment by aeons** [comment] 2016-08-01 17:11
I get a step further, and the idea seems to work, however the resource struct I get from `conn.assigns` is all `nil`s.

Any suggestions?

**Comment by smpallen99** [comment] 2016-08-01 17:19
Need to step out for the afternoon so this will be my last response until later this evening. I believe the issue is with trying to show an index page for a non-admin user. In my projects I don't usually allow this Since, IMHO it does not make sense. 

I would disable index for non-admin users, and allow non-admin users to view and update their profile through the profile link in the top right nav bar.

I'll catch up with you later this evening when I get back come. 

Steve

**Comment by aeons** [comment] 2016-08-02 10:16
I get that this is a special case for user management, but I can still see this being useful if you have some other resource where you can see all items but only modify "your own".

Anyway, I can live with everyone having access for this case.

**Comment by smpallen99** [comment] 2016-08-02 13:01
I see your point. I'll take a look at it, but might not be until next week.

**Comment by aeons** [comment] 2016-08-02 14:34
Thanks :)

**Comment by smpallen99** [comment] 2016-11-19 22:24
We have modified the authorization protocol to dispatch based on resource instead of defn. This allows more control over authorization. I've updated the authorization section in the wiki with an updated example.

I'm closing this issue. If you cannot get this working with the new authorization protocol, please reopen the issue.

**Closed by smpallen99** 2016-11-19 22:24 UTC
