### ISSUE TITLE
Integer field filter search shows result by first option only

### ISSUE THREAD

**Issue by piyushchauhan2011** [smpallen99/ex_admin#64] opened 2016-04-25 08:04 UTC
![screen shot 2016-04-25 at 6 01 27 pm](https://cloud.githubusercontent.com/assets/693487/14777377/0438cb22-0b10-11e6-846f-602a8483c363.png)

When I select `greater than` option in select menu, it default backs to `equal to` and search using that.

**Comment by smpallen99** [comment] 2016-04-25 12:29
This is a duplicate of #61 which has been fixed. Thansk

**Closed by smpallen99** 2016-04-25 12:29 UTC
Labels: duplicate
